version: "3.9"

services:
  iptv_restream_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: ""
        VITE_STREAM_DELAY: 18
        VITE_STREAM_PROXY_DELAY: 30
    networks:
      - app-network

  iptv_restream_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - streams_data:/streams
      - channels:/channels
    environment:
      STORAGE_PATH: /streams/
      #BACKEND_URL: http://iptv_restream_backend:5000
      # ADMIN_ENABLED: "true"
      # ADMIN_PASSWORD: "your_secure_password"
      # CHANNEL_SELECTION_REQUIRES_ADMIN: "true"
    networks:
      - app-network

  iptv_restream_nginx:
    image: nginx:alpine
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - streams_data:/streams
    expose:
      - "80"
    networks:
      - app-network

volumes:
  streams_data:
  channels:

networks:
  app-network:
    driver: bridge
